### ISSUE TITLE
[Bug]: deadLetter will not start for normal consumer start with while

### ISSUE THREAD

**Issue by bingtianyiyan** [EasilyNET/EasilyNET#164]
### ⚙️ OS

Windows(Default)

### ⚙️ Architecture

Any(Default)

### ⚙️ .NET Version

.NET6(LTS)

### 📄 请描述您的问题(Describe the bug).

1.if normal consumer with StartBasicConsume method have while code like while (true) Thread.Sleep(100000);
,if a integrationEvent class all have both attribute RabbitAttribute and DeadLetterAttribute, the dead consumer will not start。
<img width="795" alt="1690177123914" src="https://github.com/EasilyNET/EasilyNET/assets/48984656/4c3fd093-ec4f-4a7b-b03b-7988d73ee11a">
<img width="789" alt="1690177143559" src="https://github.com/EasilyNET/EasilyNET/assets/48984656/384913b9-d90e-4816-b7e4-3f94ec2d1463">

**Comment by joesdu** [comment]
![image](https://github.com/EasilyNET/EasilyNET/assets/13188169/d8bcf04c-fb8c-4bb1-8617-8c0f066b5a43)
In the IntegrationEventBus.cs , line 339 has an overload of the StartBasicConsume method.

**Comment by bingtianyiyan** [comment]
> ![image](https://user-images.githubusercontent.com/13188169/255508853-d8bcf04c-fb8c-4bb1-8617-8c0f066b5a43.png) In the IntegrationEventBus.cs , line 339 has an overload of the StartBasicConsume method.

I know you have overload StartBasicConsumer for deadLeter;
I mean you use while（true）thread.Sleep(10000) this code is uncorrect in register RabbitAttribute consumer ,beacuse if you ues attribute  DeadLetterAttribute and RabbitAttribute at the same time  in same class,you will find deadLeteer will not register,beacuse you use while（true）thread.Sleep(10000) for RabbitAttribute consumer in StartBasicConsumer code
<img width="795" alt="1691716351577" src="https://github.com/EasilyNET/EasilyNET/assets/48984656/c559a247-9d6e-41ff-beb0-13123b12338c">
 you have already ues Task.Factory,also consumer.Received+ { }, is not necessary to use  while（true）

**Comment by joesdu** [comment]
> > ![image](https://user-images.githubusercontent.com/13188169/255508853-d8bcf04c-fb8c-4bb1-8617-8c0f066b5a43.png) In the IntegrationEventBus.cs , line 339 has an overload of the StartBasicConsume method.
> 
> I know you have overload StartBasicConsumer for deadLeter; I mean you use while（true）thread.Sleep(10000) this code is unnecessary register RabbitAttribute consumer ,beacuse if you ues attribute DeadLetterAttribute and RabbitAttribute at the same time in same class,you will find deadLeteer will not register,beacuse you use while（true）thread.Sleep(10000) for RabbitAttribute consumer in StartBasicConsumer code <img alt="1691716351577" width="795" src="https://user-images.githubusercontent.com/48984656/259904258-c559a247-9d6e-41ff-beb0-13123b12338c.png"> you have already ues Task.Factory,also consumer.Received+ { }, is not necessary to use while（true） <img alt="1691717042228" width="901" src="https://user-images.githubusercontent.com/48984656/259905196-64b868b4-7aaa-46b4-a60b-f9c377fd1b59.png">

确实存在问题.一会修好发布新版
