### ISSUE TITLE
[Bug]: 牛逼啊

### ISSUE THREAD

**Issue by wjkhappy14** [EasilyNET/EasilyNET#191]
### ⚙️ OS

Windows(Default)

### ⚙️ Architecture

Any(Default)

### ⚙️ .NET Version

.NET7(STS)

### 📄 请描述您的问题(Describe the bug).

太牛逼了啊

### ⭕ BUG 重现(To Reproduce).

大大的牛逼

### 📱 您的联系方式(Contact Details).

angkor.wu@live.com

**Comment by joesdu** [comment]
> ### ⚙️ OS
> Windows(Default)
> 
> ### ⚙️ Architecture
> Any(Default)
> 
> ### ⚙️ .NET Version
> .NET7(STS)
> 
> ### 📄 请描述您的问题(Describe the bug).
> 太牛逼了啊
> 
> ### ⭕ BUG 重现(To Reproduce).
> 大大的牛逼
> 
> ### 📱 您的联系方式(Contact Details).
> [angkor.wu@live.com](mailto:angkor.wu@live.com)

😲
