### ISSUE TITLE
[Bug]: 程序集反射冲突问题

### ISSUE THREAD

**Issue by wch66** [EasilyNET/EasilyNET#66]
### ⚙️ OS

Windows(Default)

### ⚙️ Architecture

x64

### ⚙️ .NET Version

.NET6(LTS)

### 📄 请描述您的问题(Describe the bug).

作者你好，我在使用EasilyNet.RabbitBus时，发现内部使用的AssemblyHelper获取程序集时，与我本身的框架结构内依赖注入时使用的程序集构造出现了冲突，如下图：
![A9)TN%8~2V6YQ4S{CB$LYJ](https://user-images.githubusercontent.com/36251958/230828325-e51a687d-4a7f-480c-9f03-b8a28d4aba9c.png)

### ⭕ BUG 重现(To Reproduce).

我可以提供框架内使用的依赖注入库

**Comment by joesdu** [comment]
1.3.8中已添加排除方案
```csharp
AssemblyHelper.AddExcludeLibs("Npgsql.");
var builder = WebApplication.CreateBuilder(args);
...
var app = builder.Build();
...
app.Run();
```
